### PR TITLE
Add deploy to staging via aws s3 cli

### PR DESCRIPTION
**Pull request by giorgiosironi**
~https://staging-elife-reproducible-document-stack.s3.amazonaws.com/example.html (will be wrapped by a Fastly CDN later).~

https://staging--cdn-rds.elifesciences.org/example.html

### CODE REVIEW

**Comment by giorgiosironi** [comment]
http://staging-elife-reproducible-document-stack.s3.amazonaws.com/example.html but have to exclude `.git` from being deployed and possibly deactivate the listing of files.

**Comment by giorgiosironi** [comment]
According to https://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteEndpoints.html#WebsiteRestEndpointDiff the website hosting option for S3 does not support HTTPS. Hence we should use the classic http://staging-elife-reproducible-document-stack.s3.amazonaws.com URL, but we can't serve an homepage on `/` (can always decorate it with Fastly if strictly needed).

**Comment by de-code** [comment]
I'm just interested in how this works. I thought Stencila was mostly client only. Could this be setup as a github page?

**Comment by giorgiosironi** [comment]
Yes, the `gh-pages` is being deployed by Github, but we use an eLife staging&production environment to get logs, metrics, etc.

**Comment by giorgiosironi** [comment]
The Fastly CDN will come separately, but this deploys as expected.

**Comment by davidcmoulton** [comment]
~~This PR is requesting to be merged into `develop`, is this correct? I ask because `develop` is many commits behind `master` and `gh-pages` branches.~~ Ignore this. I see now.

**Review by davidcmoulton — APPROVED** [review]
This repo's default branch will need to be changed from `gh-pages` to `develop` once this PR is merged.

**Comment by giorgiosironi** [comment]
Yes, https://alfred.elifesciences.org/job/test-rds-example/ is temporarily pointed to this branch rather than `develop` to fully test the PR; as a side effect `gh-pages`, `approved` and `master` all get updated with this branch's content at every new commit.

Once this is in `develop` it will become the source branch for that pipeline. Everything in `gh-pages` has to be merged here, to avoid the second stage of the pipeline failing to push to it.

**Pull request merged**
